ValorantReddit/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('reddit.urls')),
    path('blog/', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.list, name="index"),
    path('post/<int:id>/', views.viewPost, name='post'),
    path('profile', views.loadProfile, name='profile'),
]

blog/models.py
from ckeditor.fields import RichTextField
from django.db import models

# Create your models here.
from reddit.models import User

class Topic(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    background_color_code = models.CharField(max_length=20, default="#007bff")
    font_color_code = models.CharField(max_length=20, default="#ffffff")

class Post(models.Model):
    title = models.CharField(max_length=50)
    body = models.TextField()
    post_date = models.DateTimeField(auto_now_add=True)
    rate = models.IntegerField(range(0, 5))
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    topic = models.ManyToManyField(Topic)

class Viewer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

class Comment(models.Model):
    viewer = models.ForeignKey(Viewer, on_delete=models.CASCADE)
    reply_to = models.ForeignKey(Viewer, on_delete=models.CASCADE, null=True, related_name="reply_to")
    tag_to = models.ManyToManyField(User)
    # content = models.TextField()
    content = RichTextField()
    comment_date = models.DateTimeField(auto_now_add=True)
    rate = models.IntegerField(range(0, 5), default=0)
    reply_comment = models.ForeignKey('self', on_delete=models.CASCADE, null=True)

blog/viewmodel/forms.py
from django import forms
from django.forms import ModelForm

from blog.models import Comment


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

blog/views.py
from django.http import Http404
from django.shortcuts import render

# Create your views here.
from blog.domain import PostDomain
from blog.viewmodel.forms import CommentForm
from reddit.domain import UserDomain


def loadProfile(request):
    user = request.user
    if request.method == 'POST':
        print(len(request.FILES))
        avatar = request.FILES.get('avatar_image', None)
        if avatar:
            userDomain = UserDomain()
            userDomain.UploadAvatar(user, avatar)

    if user.is_authenticated:
        postDomain = PostDomain()

        posts = postDomain.GetPostsByAuthor(user)
        profile = postDomain.GetAuthorInfor(user)
        result = {'posts': posts, 'profile': profile}
        return render(request, 'pages/profile.html', {'result': result})
    else:
        raise Http404('')


def list(request):
    postDomain = PostDomain()
    userDomain = UserDomain()

    topUser = userDomain.LoadTopUser(4)
    result = {'posts': postDomain.GetListPost(), 'top_users': topUser}

    return render(request, 'pages/index.html', {'result': result})


def viewPost(request, id):
    user = request.user
    postDomain = PostDomain()
    postDomain.ProccessNewViewer(id, user)

    if request.method == 'POST':
        if request.POST.get('comment_button'):
            txt_comment = request.POST['comment']
            postDomain.CommentPost(id, user, txt_comment)
        elif request.POST.get('reply_button'):
            comment_id = request.POST['comment_id']
            txt_comment = request.POST['comment']
            if (txt_comment != ''):
                postDomain.ReplyComment(post_id=id, txt_comment=txt_comment, comment_id=comment_id, user=user)

    commentForm = CommentForm()
    post = postDomain.GetPostById(id)
    author = postDomain.GetAuthorInfor(post.author)
    result = {'post': postDomain.ViewPost(id, user), 'comment_form': commentForm, 'author': author}
    return render(request, 'pages/post.html', {'result': result})

blog/templates/shares/home_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base_home.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/post.css' %}">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/fd7decadf7.js" crossorigin="anonymous"></script>
    <title>Title</title>
</head>
<header>
    <div class="row">
        <img src="{% static 'images/valorant-icon.jpg' %}" class="valorant-icon">
        <img src="{% static 'images/valorant-text.png' %}" class="valorant-text">
    </div>
</header>
<body>
<div class="container">
    <div class="row">
        {% block content %}
        {% endblock %}
        {% if result.top_users %}
        <div class="col-4">
            <div class="container top-user-container" style="width: 90%">
                <div class="row top-user-banner"><span>Most Viewed Users</span></div>
                {% for key_user in result.top_users %}
                <div class="row user-container" style="">
                    <div class="col-8">
                        <div>
                            <span class="small-black-bold-text">{{ key_user.first_name }} {{ key_user.last_name }} {% if forloop.counter == 1 %} <i
                                    class="fas fa-crown crown-icon"></i> {% endif %}</span>
                        </div>
                        <div><span class="small-grey-text">{{ key_user.email }}</span></div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}
        {% if result.author %}
        {% with author=result.author %}
        <div class="col-4">
            <div class="container author-container">
                <div class="row author-banner"></div>
                <div class="row author-information-container">
                    <div class="col-2">

                    </div>
                    <div class="col-10">
                        <div class="row">
                            <span class="medium-black-bold-text">{{ author.first_name }} {{ author.last_name }}</span>
                        </div>
                        <div class="row">
                            <span class="small-grey-text">{{ author.email }}</span>
                        </div>
                    </div>
                </div>
                <div class="row author-award-container">
                    <div class="col-6">
                        <div class="row">
                            <span class="medium-black-bold-text">{{ author.numOfPosts }}</span>
                        </div>
                        <div class="row">
                            <span class="small-black-bold-text">Posts</span>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="row">
                            <span class="medium-black-bold-text">{{ author.numOfViews }}</span>
                        </div>
                        <div class="row">
                            <span class="small-black-bold-text">Views</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endwith %}
        {% endif %}
        {% if result.profile %}
        {% with profile=result.profile %}
        <div class="col-4">
            <div class="container profile-container">
                <div class="row profile-banner">
                    <div class="col-4" style="padding: 0">
                        <form action="{% url 'blog:profile' %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <input hidden type="file" id="avatar" name="avatar_image">
                            <input hidden type="submit" id="upload_avatar_button">
                        </form>
                    </div>
                    <div class="col-8" style="padding: 0">
                        <i class="fas fa-camera avatar-add-icon" onclick="chooseImage()"></i>
                    </div>
                </div>
                <div class="row profile-information-container">
                    <div class="avatar-container">
                        <img src="{{ profile.avatar }}" class="avatar" onclick="chooseImage()">
                    </div>
                    <div class="col-4" style="padding: 0">

                    </div>
                    <div class="col-8" style="padding: 0">
                        <div class="row">
                            <span class="small-black-bold-text">{{ profile.first_name }} {{ profile.last_name }}</span>
                        </div>
                        <div class="row">
                            <span class="small-grey-text">{{ profile.email }}</span>
                        </div>
                    </div>
                </div>
                <div class="row profile-award-container">
                    <div class="col-6">
                        <div class="row">
                            <span class="medium-black-bold-text">{{ profile.numOfPosts }}</span>
                        </div>
                        <div class="row">
                            <span class="small-black-bold-text">Posts</span>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="row">
                            <span class="medium-black-bold-text">{{ profile.numOfViews }}</span>
                        </div>
                        <div class="row">
                            <span class="small-black-bold-text">Views</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endwith %}
        {% endif %}
    </div>
</div>
</body>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript">
    function chooseImage(){
        $("#avatar").change(function(e){
            $("#upload_avatar_button").trigger('click');
         });
        $('#avatar').trigger('click');
    }
</script>
</html>