ValorantReddit/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('reddit.urls')),
    path('blog/', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.list, name="index"),
    path('post/<int:id>/', views.viewPost, name='post'),
    path('profile', views.loadProfile, name='profile'),
]

blog/models.py
from ckeditor.fields import RichTextField
from django.db import models

# Create your models here.
from reddit.models import User

class Topic(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    background_color_code = models.CharField(max_length=20, default="#007bff")
    font_color_code = models.CharField(max_length=20, default="#ffffff")

class Post(models.Model):
    title = models.CharField(max_length=50)
    body = models.TextField()
    post_date = models.DateTimeField(auto_now_add=True)
    rate = models.IntegerField(range(0, 5))
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    topic = models.ManyToManyField(Topic)

class Viewer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

class Comment(models.Model):
    viewer = models.ForeignKey(Viewer, on_delete=models.CASCADE)
    reply_to = models.ForeignKey(Viewer, on_delete=models.CASCADE, null=True, related_name="reply_to")
    tag_to = models.ManyToManyField(User)
    # content = models.TextField()
    content = RichTextField()
    comment_date = models.DateTimeField(auto_now_add=True)
    rate = models.IntegerField(range(0, 5), default=0)
    reply_comment = models.ForeignKey('self', on_delete=models.CASCADE, null=True)

blog/viewmodel/forms.py
from django import forms
from django.forms import ModelForm

from blog.models import Comment


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

blog/views.py
from django.http import Http404
from django.shortcuts import render

# Create your views here.
from blog.domain import PostDomain
from blog.viewmodel.forms import CommentForm
from reddit.domain import UserDomain


def loadProfile(request):
    user = request.user
    if request.method == 'POST':
        print(len(request.FILES))
        avatar = request.FILES.get('avatar_image', None)
        if avatar:
            userDomain = UserDomain()
            userDomain.UploadAvatar(user, avatar)

    if user.is_authenticated:
        postDomain = PostDomain()

        posts = postDomain.GetPostsByAuthor(user)
        profile = postDomain.GetAuthorInfor(user)
        result = {'posts': posts, 'profile': profile}
        return render(request, 'pages/profile.html', {'result': result})
    else:
        raise Http404('')


def list(request):
    postDomain = PostDomain()
    userDomain = UserDomain()

    topUser = userDomain.LoadTopUser(4)
    result = {'posts': postDomain.GetListPost(), 'top_users': topUser}

    return render(request, 'pages/index.html', {'result': result})


def viewPost(request, id):
    user = request.user
    postDomain = PostDomain()
    postDomain.ProccessNewViewer(id, user)

    if request.method == 'POST':
        if request.POST.get('comment_button'):
            txt_comment = request.POST['comment']
            postDomain.CommentPost(id, user, txt_comment)
        elif request.POST.get('reply_button'):
            comment_id = request.POST['comment_id']
            txt_comment = request.POST['comment']
            if (txt_comment != ''):
                postDomain.ReplyComment(post_id=id, txt_comment=txt_comment, comment_id=comment_id, user=user)

    commentForm = CommentForm()
    post = postDomain.GetPostById(id)
    author = postDomain.GetAuthorInfor(post.author)
    result = {'post': postDomain.ViewPost(id, user), 'comment_form': commentForm, 'author': author}
    return render(request, 'pages/post.html', {'result': result})

blog/templates/pages/index.html
{% extends "shares/home_base.html" %}
{% block content %}
{% if request.user.is_authenticated %}
<div class="col-8">
    <div class="container post-create-container">
        <div class="row">
            <div class="col-8 post-create-btn">
                <span class="small-grey-text">{{ request.user.last_name }}, something news today?</span>
            </div>
            <div class="vertical-slim-grey-line"></div>
            <div class="post-create-icon-container">
                <i class="fas fa-photo-video photo-icon" style="line-height: 220%"></i>
                <span class="small-grey-bold-text">Photo</span>
            </div>
            <div class="post-create-icon-container">
                <i class="far fa-grin emotion-icon" style="line-height: 220%"></i>
                <span class="small-grey-bold-text">Emotion</span>
            </div>
        </div>
    </div>
    {% endif %}
    {% for post in result.posts %}
    <div class="container post-container" onclick="goToDetail({{ post.id }})">
        <div class="row post-info">
            {% for topic in post.topic %}
            <span class="badge badge-primary topic-badge"
                  style="background-color: {{ topic.background_color_code }}; color: {{ topic.font_color_code }}">
        {{ topic.name }}
        </span> {% endfor %}
            <div class="small-grey-text">Posted by {{ post.author.first_name }} {{ post.author.last_name }}</div>
            <div class="small-grey-text">{{ post.time_display }}</div>
        </div>
        <div class="row post-title-container">
            <div class="medium-black-bold-text">{{ post.title }}</div>
        </div>
        <div class="row post-body-container">
            <div class="post-body">{{ post.body }}</div>
        </div>
        <div class="row">
            <div class="comment-container">
                <i class="far fa-comment-alt comment-icon"></i>
                <span class="small-grey-bold-text">{{ post.numOfComments }} Comments</span>
            </div>
            <div class="eye-container">
                <i class="far fa-eye eye-icon"></i>
                <span class="small-grey-bold-text">{{ post.numOfViews }} Views</span>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<script type="text/javascript">
    function goToDetail(id){
        window.location.href = 'post/' +id;
    }

</script>

{% endblock %}

blog/templates/pages/post.html
{% extends "shares/home_base.html" %}
{% block content %}
<style>
body{
    background-color: #f6f6f6;
}
.post-container{
    margin-bottom: 0;
    border: 0;
    border-radius: 0;
    border-top-left-radius: 5px;
    border-top-right-radius: 5px;
}
.post-container:hover{
    border: 0;
    cursor: default;
}





</style>
{% with post=result.post %}
<div class="col-8">
    <div class="container post-container">
        <div class="row post-info">
            {% for topic in post.topic %}
            <span class="badge badge-primary topic-badge"
                  style="background-color: {{ topic.background_color_code }}; color: {{ topic.font_color_code }}">
        {{ topic.name }}
        </span> {% endfor %}
            <div class="small-grey-text">Posted by {{ post.author.first_name }} {{ post.author.last_name }}</div>
            <div class="small-grey-text">{{ post.time_display }}</div>
        </div>
        <div class="row post-title-container">
            <div class="medium-black-bold-text">{{ post.title }}</div>
        </div>
        <div class="row post-body-container">
            <div class="post-body">{{ post.body }}</div>
        </div>
        <div class="row">
            <div class="comment-container">
                <i class="far fa-comment-alt comment-icon"></i>
                <span class="small-grey-bold-text">{{ post.numOfComments }} Comments</span>
            </div>
            <div class="eye-container">
                <i class="far fa-eye eye-icon"></i>
                <span class="small-grey-bold-text">{{ post.numOfViews }} Views</span>
            </div>
        </div>
    </div>
    <div class="container comment-form-container">
        <form action="{% url 'blog:post' post.id %}" method="post">
            {% csrf_token %}
            {{ result.comment_form.media }}
            <!--            {{ result.comment_form }}-->
            <label><span
                    class="small-black-text">Comment as {{ request.user.first_name }} {{ request.user.last_name }}</span>
            </label><br>
            <div style="padding-right: 15px; padding-left: 15px">
                <textarea class="ckeditor" name="comment" style="width: 650px, height: 190px"></textarea>
            </div>
            <input class="btn btn-outline-dark btn-sm" type="submit" value="comment" name="comment_button"
                   style="margin-top: 15px; margin-bottom: 10px">
        </form>
    </div>
    <div class="container list-comment-container">
        {% for comment in post.list_comment %}
        <div id="{{ comment.id }}" class="comment">
            <div class="row">
                <div class="comment-avatar">
                    <img src="{{ comment.viewer.user.avatar }}">
                </div>
                <div>
                    <span class="small-black-text" style="margin-right: 5px; margin-left: 5px">{{ comment.viewer.user.first_name }} {{ comment.viewer.user.last_name }}</span>
                    <span class="small-grey-text">{{ comment.time_display }}</span>
                </div>
            </div>
            <div class="row comment-content-container">
                <span>{{ comment.content }}</span>
            </div>
            <div class="row reply-button" onclick="replyComment({{ comment.id }})">
                <span class="small-grey-text">Reply</span>
            </div>
        </div>
        <div hidden id="reply_{{ comment.id }}" class="reply-form-container">
            <form action="{% url 'blog:post' post.id %}" method="post">
                {% csrf_token %}
                {{ result.comment_form.media }}
                <label><span
                        class="small-black-text">Comment as {{ request.user.first_name }} {{ request.user.last_name }}</span>
                </label><br>
                <div style="padding-right: 15px; padding-left: 15px">
                    <textarea class="ckeditor" name="comment" style="width: 650px, height: 190px"></textarea>
                </div>
                <input type="hidden" name="comment_id" value="{{ comment.id }}">
                <input class="btn btn-outline-dark btn-sm" type="submit" value="reply" name="reply_button"
                       style="margin-top: 15px; margin-bottom: 10px">
                <input class="btn btn-outline-danger btn-sm" type="button" value="cancel" name="cancel_button"
                       style="margin-top: 15px; margin-bottom: 10px" onclick="cancelReply({{ comment.id }})">
            </form>
        </div>
        {% for reply in comment.replies %}
        <div id="{{ reply.id }}" class="reply">
            <div class="row">
                <div class="comment-avatar">
                    <img src="{{ comment.viewer.user.avatar }}">
                </div>
                <div>
                    <span class="small-black-text" style="margin-right: 5px; margin-left: 5px">{{ reply.viewer.user.first_name }} {{ reply.viewer.user.last_name }}</span>
                    <span class="small-grey-text">{{ reply.time_display }}</span>
                </div>
            </div>
            <div class="row comment-content-container">
                <span>
                    {% if reply.reply_to != None %}
                    <span class="super-small-black-bold-text">{{ reply.reply_to.user.first_name }} {{ reply.reply_to.user.last_name }}</span>
                    {% endif %}
                    {{ reply.content }}
                </span>
            </div>
            <div class="row reply-button" onclick="replyComment({{ reply.id }})">
                <span class="small-grey-text">Reply</span>
            </div>
        </div>
        <div hidden id="reply_{{ reply.id }}" class="reply-form-container">
            <form action="{% url 'blog:post' post.id %}" method="post">
                {% csrf_token %}
                {{ result.comment_form.media }}
                <label><span
                        class="small-black-text">Comment as {{ request.user.first_name }} {{ request.user.last_name }}</span>
                </label><br>
                <div style="padding-right: 15px; padding-left: 15px">
                    <textarea class="ckeditor" id="comment" name="comment"
                              style="width: 650px, height: 190px"></textarea>
                </div>
                <input type="hidden" name="comment_id" value="{{ comment.id }}">
                <input class="btn btn-outline-dark btn-sm" type="submit" value="reply" name="reply_button"
                       style="margin-top: 15px; margin-bottom: 10px">
                <input class="btn btn-outline-danger btn-sm" type="button" value="cancel" name="cancel_button"
                       style="margin-top: 15px; margin-bottom: 10px" onclick="cancelReply({{ reply.id }})">
            </form>
        </div>
        {% endfor %}
        {% endfor %}
    </div>
</div>
{% endwith %}
<script type="text/javascript">
    reply_div_block = document.createElement('div');

    function replyComment(id){
        reply_div = document.getElementById("reply_"+id);
        if(reply_div.hidden){
            reply_div_block.hidden = true
            reply_div.removeAttribute("hidden")
            reply_div_block = reply_div
        }else{
            reply_div.hidden = true
        }

    }

    function cancelReply(id){
        reply_div = document.getElementById("reply_"+id);
        reply_div.hidden = true
    }




</script>
{% endblock %}

blog/templates/pages/profile.html
{% extends "shares/home_base.html" %}
{% block content %}
{% if request.user.is_authenticated %}
<div class="col-8">
    <div class="container post-create-container">
        <div class="row">
            <div class="col-8 post-create-btn">
                <span class="small-grey-text">{{ request.user.last_name }}, something news today?</span>
            </div>
            <div class="vertical-slim-grey-line"></div>
            <div class="post-create-icon-container">
                <i class="fas fa-photo-video photo-icon" style="line-height: 220%"></i>
                <span class="small-grey-bold-text">Photo</span>
            </div>
            <div class="post-create-icon-container">
                <i class="far fa-grin emotion-icon" style="line-height: 220%"></i>
                <span class="small-grey-bold-text">Emotion</span>
            </div>
        </div>
    </div>
    {% endif %}
    {% for post in result.posts %}
    <div class="container post-container" onclick="goToDetail({{ post.id }})">
        <div class="row post-info">
            {% for topic in post.topic %}
            <span class="badge badge-primary topic-badge"
                  style="background-color: {{ topic.background_color_code }}; color: {{ topic.font_color_code }}">
        {{ topic.name }}
        </span> {% endfor %}
            <div class="small-grey-text">Posted by {{ post.author.first_name }} {{ post.author.last_name }}</div>
            <div class="small-grey-text">{{ post.time_display }}</div>
        </div>
        <div class="row post-title-container">
            <div class="medium-black-bold-text">{{ post.title }}</div>
        </div>
        <div class="row post-body-container">
            <div class="post-body">{{ post.body }}</div>
        </div>
        <div class="row">
            <div class="comment-container">
                <i class="far fa-comment-alt comment-icon"></i>
                <span class="small-grey-bold-text">{{ post.numOfComments }} Comments</span>
            </div>
            <div class="eye-container">
                <i class="far fa-eye eye-icon"></i>
                <span class="small-grey-bold-text">{{ post.numOfViews }} Views</span>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<script type="text/javascript">
    function goToDetail(id){
        window.location.href = 'post/' +id;
    }

</script>

{% endblock %}